import React from 'react'
import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home(props) {
  console.log(props)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {props.films && props.films.map(item => {
        return (
          <div key={item.filmId}>{item.name}
          </div>
        )
      })}
    </div>
  )
}


Home.getInitialProps = async () => {
  const res = await axios.get('https://m.maizuo.com/gateway?cityId=440100&pageNum=1&pageSize=10&type=1&k=3452262', {
    headers: {
      'X-Host': 'mall.film-ticket.film.list'
    }
  })
  console.log(res)
  return {
    films: [...res.data.data.films]
  }
}
